[package]
name = "decker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.3.2"
rand = "0.8.3"
once_cell = "1.7.2"
serde = "1.0.126"
log = "0.4.14"
fern = "0.6.0"
chrono = "0.4.19"
serde_json = "1.0.64"
